import { log } from '../config/logger';
/**
 * AfriBourse — Weekly Watchlist IA Email Summary
 * Runs every Monday at 08h00.
 * Sends each user with a watchlist a personalised HTML email:
 *   • Performance recap (P&L, best/worst)
 *   • Signal scores heatmap
 *   • Short IA text generated by Groq
 */

import prisma from '../config/prisma';
import { sendEmail } from './email.service';
import { getWatchlistEnriched } from './watchlist.service.prisma';
import { getWatchlistScores } from './watchlist.scores';
import config from '../config/environnement';
import { generateWatchlistSummary } from './simba-micro';

// ── Zone badge helper ──────────────────────────────────────────────────────────

function zoneBadge(zone: string): string {
  const map: Record<string, string> = {
    'Achat Fort':   '#10b981',
    'Signal Achat': '#22c55e',
    'Neutre':       '#9ca3af',
    'Signal Vente': '#f97316',
    'Vente Forte':  '#ef4444',
  };
  const color = map[zone] ?? '#9ca3af';
  return `<span style="background:${color};color:#fff;font-size:10px;font-weight:700;padding:2px 7px;border-radius:20px;">${zone}</span>`;
}

// ── Build HTML email ───────────────────────────────────────────────────────────

function buildEmailHTML(
  userName: string,
  items: any[],
  scores: any[],
  simbaSummary: string
): string {
  const scoreMap = Object.fromEntries(scores.map(s => [s.ticker, s]));
  const now = new Date().toLocaleDateString('fr-FR', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });

  const rows = items.map(item => {
    const s = scoreMap[item.stock_ticker];
    const price = item.current_price
      ? new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 0 }).format(item.current_price) + ' FCFA'
      : '–';
    const pnl = item.pnl_pct != null
      ? `<span style="color:${item.pnl_pct >= 0 ? '#10b981' : '#ef4444'};font-weight:700;">${item.pnl_pct >= 0 ? '+' : ''}${item.pnl_pct.toFixed(2)}%</span>`
      : '<span style="color:#9ca3af;">–</span>';
    const change = item.change_pct != null
      ? `<span style="color:${item.change_pct >= 0 ? '#10b981' : '#ef4444'};">${item.change_pct >= 0 ? '+' : ''}${item.change_pct.toFixed(2)}%</span>`
      : '–';
    const badge = s ? zoneBadge(s.zone) : '';
    const score = s ? `<b style="font-size:15px;">${s.score}</b><span style="color:#9ca3af;font-size:11px;">/100</span>` : '–';

    return `
      <tr style="border-bottom:1px solid #f3f4f6;">
        <td style="padding:10px 12px;font-weight:700;font-size:13px;">${item.stock_ticker}</td>
        <td style="padding:10px 12px;font-size:13px;">${price}</td>
        <td style="padding:10px 12px;font-size:13px;">${change}</td>
        <td style="padding:10px 12px;font-size:13px;">${pnl}</td>
        <td style="padding:10px 12px;text-align:center;">${score}</td>
        <td style="padding:10px 12px;">${badge}</td>
      </tr>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="fr">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:'Segoe UI',Arial,sans-serif;">
<div style="max-width:620px;margin:0 auto;padding:24px 16px;">

  <!-- Header -->
  <div style="background:linear-gradient(135deg,#1e3a5f 0%,#2563eb 100%);border-radius:16px;padding:28px 24px;text-align:center;margin-bottom:20px;">
    <p style="color:#93c5fd;font-size:12px;text-transform:uppercase;letter-spacing:2px;margin:0 0 6px;">AfriBourse · SIMBA IA</p>
    <h1 style="color:#fff;font-size:22px;margin:0 0 6px;">Résumé hebdomadaire</h1>
    <p style="color:#bfdbfe;font-size:13px;margin:0;">${now}</p>
  </div>

  <!-- Greeting -->
  <div style="background:#fff;border-radius:16px;padding:20px 24px;margin-bottom:16px;border:1px solid #e5e7eb;">
    <p style="font-size:15px;color:#1f2937;margin:0 0 6px;">Bonjour <strong>${userName}</strong>,</p>
    <p style="font-size:14px;color:#4b5563;margin:0;">Voici le bilan de votre watchlist pour la semaine écoulée.</p>
  </div>

  ${simbaSummary ? `
  <!-- SIMBA comment -->
  <div style="background:#eff6ff;border-left:4px solid #2563eb;border-radius:12px;padding:16px 20px;margin-bottom:16px;">
    <p style="font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#2563eb;font-weight:700;margin:0 0 6px;">💬 SIMBA IA</p>
    <p style="font-size:14px;color:#1e3a5f;margin:0;line-height:1.6;">${simbaSummary}</p>
  </div>` : ''}

  <!-- Table -->
  <div style="background:#fff;border-radius:16px;overflow:hidden;border:1px solid #e5e7eb;margin-bottom:16px;">
    <div style="padding:14px 20px;border-bottom:1px solid #f3f4f6;">
      <p style="font-weight:700;font-size:14px;color:#111827;margin:0;">📊 Votre Watchlist (${items.length} valeur${items.length > 1 ? 's' : ''})</p>
    </div>
    <table style="width:100%;border-collapse:collapse;">
      <thead>
        <tr style="background:#f9fafb;">
          <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;text-transform:uppercase;letter-spacing:.5px;">Ticker</th>
          <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;text-transform:uppercase;letter-spacing:.5px;">Prix</th>
          <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;text-transform:uppercase;letter-spacing:.5px;">Var. jour</th>
          <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;text-transform:uppercase;letter-spacing:.5px;">P&L</th>
          <th style="padding:8px 12px;text-align:center;font-size:11px;color:#6b7280;font-weight:600;text-transform:uppercase;letter-spacing:.5px;">Score</th>
          <th style="padding:8px 12px;text-align:left;font-size:11px;color:#6b7280;font-weight:600;text-transform:uppercase;letter-spacing:.5px;">Signal</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
  </div>

  <!-- CTA -->
  <div style="text-align:center;margin-bottom:20px;">
    <a href="${config.app.frontendUrl}/watchlist"
       style="display:inline-block;background:#2563eb;color:#fff;font-weight:700;font-size:14px;padding:12px 28px;border-radius:12px;text-decoration:none;">
      Voir ma Watchlist →
    </a>
  </div>

  <!-- Footer -->
  <p style="text-align:center;font-size:11px;color:#9ca3af;margin:0;">
    AfriBourse · <a href="${config.app.frontendUrl}/privacy" style="color:#9ca3af;">Confidentialité</a> ·
    Ce résumé est généré automatiquement chaque lundi.
  </p>
</div>
</body></html>`;
}

// ── Main export ────────────────────────────────────────────────────────────────

export async function sendWeeklyWatchlistSummaries(): Promise<{ sent: number; skipped: number; errors: number }> {
  let sent = 0, skipped = 0, errors = 0;

  // Get all users with watchlist items + their email + name
  const usersWithWatchlist: { userId: string; user: { email: string; name: string } }[] =
    await prisma.watchlistItem.findMany({
      distinct: ['userId'],
      select: { userId: true, user: { select: { email: true, name: true } } },
    });

  for (const { userId, user } of usersWithWatchlist) {
    try {
      const [items, scores] = await Promise.all([
        getWatchlistEnriched(userId),
        getWatchlistScores(userId),
      ]);

      if (items.length === 0) { skipped++; continue; }

      const simbaSummary = await generateWatchlistSummary(items, scores);
      const html = buildEmailHTML(user.name || 'Investisseur', items, scores, simbaSummary);

      await sendEmail({
        to: user.email,
        subject: `📊 Votre watchlist cette semaine — ${items.length} valeur${items.length > 1 ? 's' : ''} suivie${items.length > 1 ? 's' : ''}`,
        html,
      });

      sent++;
      log.debug(`[WatchlistSummary] Email envoyé à ${user.email} (${items.length} tickers)`);
    } catch (err) {
      log.error(`[WatchlistSummary] Erreur pour userId ${userId}:`, err);
      errors++;
    }
  }

  return { sent, skipped, errors };
}
